openapi: 3.1.0
x-stoplight:
  id: 89kuqh6fotpoj
info:
  title: template
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/user/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
              required:
                - firstName
                - email
                - password
                - username
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    get:
      summary: ''
      operationId: get-all-users
      responses:
        '200':
          description: OK
      description: Gets all users
components:
  schemas:
    User:
      type: object
      x-examples:
        Example 1:
          _id:
            $oid: 63abdd37dba610ee7ef68dbb
          username: helloWorld
          email: charlie.dowd1996@gmail.com
          firstName: Charlie
          password: '123'
          createdAt:
            $date: '2022-12-28T06:07:51.229Z'
          updatedAt:
            $date: '2022-12-28T06:07:51.229Z'
          __v: 0
      title: User
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        firstName:
          type: string
        password:
          type: string
        _id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        lastName:
          type: string
      required:
        - username
        - email
        - firstName
        - password
        - _id
        - createdAt
        - updatedAt
    Todo:
      title: Todo
      x-stoplight:
        id: zanfjehx494u1
      type: object
      properties:
        _id:
          type: string
        completed:
          type: boolean
        task:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - _id
        - completed
        - task
        - createdAt
        - updatedAt
